---
language: java
install: true
script: $TARGET
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
jdk:
- openjdk8

env:
  matrix:
    - TARGET='mvn test -Ptravis'

notifications:
  email:
    - michael@mosmann.de
    - m.joehren@gmail.com
